PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

# questa è la sintassi giusta
SELECT ?subject ?l
	WHERE {
		?subject rdfs:subClassOf obo:FOODON_00001013.
		?subject rdfs:label ?l
	}




PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

SELECT ?subject ?o
	WHERE {
		?subject :isMadeWithRawMaterial ?o
	}