#
# List of all cheese with ripeness between 5 and 20 days
#

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://wwv.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

SELECT ?cheese (STR(?lab) AS ?label) ?duration WHERE {
    ?cheese :hasRipeness ?ripeness.
    ?ripeness :hasRipenessDuration ?duration.

    OPTIONAL {?cheese rdfs:label ?lab}
    FILTER (?duration > 5 && ?duration < 20)
}
ORDER BY ?label



#
# List of all protected name cheeses
#

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX protected: <http://w3id.org/food/ontology/disciplinare-formaggio/>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

SELECT ?cheese (STR(?lab) AS ?label) WHERE {
    ?cheese rdf:type protected:Formaggio.
    OPTIONAL {?cheese rdfs:label ?lab}
}
ORDER BY ?label



#
# List of all pit cheese
#

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

SELECT?cheese (STR(?lab) as ?label)
WHERE {
    ?cheese rdf:type ?cheeseclass.
    ?cheeseclass rdfs:label "Cheese".
    ?cheese :locatedInEnvironment ?env.
    ?env rdf:type ?envclass.
    ?envclass rdfs:label "Pit".
    OPTIONAL {?cheese rdfs:label ?lab}
}
ORDER BY ?label


#
# List of all cheese made with raw milk
#

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://wwv.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <https://github.com/nicolasfara/cheese-ontology/>

SELECT ?cheese (STR(?lab) AS ?label) ?duration WHERE {
    ?cheese :isMadeWithMilk ?milk.
    ?milk rdf:type :RawMilk.

    OPTIONAL {?cheese rdfs:label ?lab}
}
ORDER BY ?label
